=== ituvtu/Web-t-lw5/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="animalForum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="categories" type="categoriesType"/>
                <xs:element name="users" type="usersType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="categoriesType">
        <xs:sequence>
            <xs:element name="category" type="categoryType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="threads" type="threadsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="threadsType">
        <xs:sequence>
            <xs:element name="thread" type="threadType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="threadType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="posts" type="postsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="postsType">
        <xs:sequence>
            <xs:element name="post" type="postType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="postType">
        <xs:sequence>
            <xs:element name="author" type="authorType"/>
            <xs:element name="content" type="xs:string"/>
            <xs:element name="timestamp" type="xs:dateTime"/>
            <xs:element name="topic" type="xs:string"/>
            <xs:element name="keywords" type="keywordsType"/>
            <xs:element name="comments" type="commentsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="keywordsType">
    <xs:sequence>
        <xs:element name="keyword" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="authorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="userId" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="commentType">
        <xs:sequence>
            <xs:element name="author" type="authorType"/>
            <xs:element name="content" type="xs:string"/>
            <xs:element name="timestamp" type="xs:dateTime"/>
            <xs:element name="comments" type="commentsType" minOccurs="0"/> <!-- Опціональний елемент для вкладених коментарів -->
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="commentsType">
        <xs:sequence>
            <xs:element name="comment" type="commentType" maxOccurs="unbounded"/> <!-- Дозволяє необмежену кількість вкладених коментарів -->
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="usersType">
        <xs:sequence>
            <xs:element name="user" type="userType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="userType">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="joinedDate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== ituvtu/Web-t-lw5/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<animalForum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <categories>
        <!-- Категорії та теми -->
        <category id="cats">
            <title>Кішки</title>
            <threads>
                <thread id="thread1">
                    <title>Породи кішок</title>
                    <posts>
                        <post id="post1">
                            <author userId="user1">Користувач1</author>
                            <content>Сіамські кішки мають неймовірне забарвлення.</content>
                            <timestamp>2023-03-15T12:00:00</timestamp>
                            <topic>Породи кішок</topic>
                            <keywords>
                                <keyword>сіамські кішки</keyword>
                                <keyword>забарвлення</keyword>
                                <keyword>породи</keyword>
                            </keywords>
                            <comments>
                                <comment id="comment1">
                                    <author userId="user2"></author>
                                    <content>Так, вони дуже красиві!</content>
                                    <timestamp>2023-03-15T12:30:00</timestamp>
                                </comment>
                                <comment id="comment2">
                                    <author userId="user2"></author>
                                    <content>хахаха</content>
                                    <timestamp>2023-03-15T12:30:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                        <post id="post2">
                            <author userId="user1">Користувач1</author>
                            <content>Кішки приємно мурликають.</content>
                            <timestamp>2023-03-15T12:00:00</timestamp>
                            <topic>Породи кішок</topic>
                            <keywords>
                                <keyword>кішки</keyword> 
                               <keyword>муркотіння</keyword> 
                            </keywords>
                            <comments>
                                <comment id="comment1">
                                    <author userId="user2">Користувач2</author>
                                    <content>Так, вони дуже гарні звуки роблять!</content>
                                    <timestamp>2023-03-15T12:30:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                        <post id="post3">
                            <author userId="user1">Користувач1</author>
                            <content>Які породи кішок найбільш дружелюбні?</content>
                            <timestamp>2023-03-15T08:00:00</timestamp>
                            <topic>Породи кішок</topic>
                            <keywords> 
                                <keyword>дружелюбність</keyword> 
                                <keyword>породи кішок</keyword> 
                            </keywords>
                            <comments>
                                <comment id="comment3-1">
                                    <author userId="user2">Користувач2</author>
                                    <content>Мені здається, мейн-куни дуже доброзичливі.</content>
                                    <timestamp>2023-03-15T08:30:00</timestamp>
                                </comment>
                                <comment id="comment3-2">
                                    <author userId="user3">Користувач3</author>
                                    <content>Сфінкси також дуже ласкаві!</content>
                                    <timestamp>2023-03-15T09:15:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                        <post id="post4">
                            <author userId="user4">Користувач4</author>
                            <content>Чим краще годувати стерилізовану кішку?</content>
                            <timestamp>2023-03-15T10:00:00</timestamp>
                            <topic>Догляд за кішками</topic>
                            <keywords>
                                <keyword>стерилізована кішка</keyword> 
                                <keyword>годування</keyword> 
                            </keywords>
                            <comments>
                                <comment id="Comment4-1">
                                    <author userId="user5">Користувач5</author>
                                    <content>Ветеринари зазвичай рекомендують спеціальний корм для стерилізованих кішок.</content>
                                    <timestamp>2023-03-15T10:45:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                        <post id="post5">
                            <author userId="user5">Користувач4</author>
                            <content>Як розважити котика?</content>
                            <timestamp>2023-03-15T10:00:00</timestamp>
                            <topic>Розваги для кішок</topic>
                            <keywords>
                                <keyword>розваги</keyword> 
                                <keyword>котик</keyword> 
                                <keyword>іграшки</keyword> 
                            </keywords>
                            <comments>
                                <comment id="Comment5-1">
                                    <author userId="user5">Користувач5</author>
                                    <content>Ветеринари зазвичай рекомендують спеціальні іграшки.</content>
                                    <timestamp>2023-03-15T10:45:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                    </posts>
                </thread>
            </threads>
        </category>

        <category id="dogs">
            <title>Собаки</title>
            <threads>
                <thread id="thread2">
                    <title>Догляд за собаками</title>
                    <posts>
                        <post id="post1">
                            <author userId="user2">Користувач2</author>
                            <content>Найкращий корм для активних собак.</content>
                            <timestamp>2023-03-16T11:00:00</timestamp>
                            <topic>Догляд за собаками</topic>
                            <keywords>
                                <keyword>корм</keyword> 
                                <keyword>активні собаки</keyword> 
                                <keyword>годування</keyword> 
                            </keywords>
                            <comments>
                                <comment id="comment2-1-1">
                                    <author userId="user4">Користувач4</author>
                                    <content>У мене теж є собака, вона дуже активна.</content>
                                    <timestamp>2023-03-15T14:00:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                        <post id="post2">
                            <author userId="user2">Користувач2</author>
                            <content>Що робити, якщо не лягає не спати?</content>
                            <timestamp>2023-03-16T11:00:00</timestamp>
                            <topic>Догляд за собаками</topic>
                            <keywords>
                                <keyword>сон</keyword> 
                                <keyword>проблеми зі сном</keyword> 
                                <keyword>собака</keyword> 
                            </keywords>
                            <comments>
                                <comment id="comment2-1-1">
                                    <author userId="user4">Користувач4</author>
                                    <content>Спробувати заспокоїти собаку обіймами.</content>
                                    <timestamp>2023-03-15T14:00:00</timestamp>
                                </comment>
                            </comments>
                        </post>
                        
                        <post id="post3">
                            <author userId="user2">Користувач2</author>
                            <content>Що робити при страху купатися?</content>
                            <timestamp>2023-03-16T11:00:00</timestamp>
                            <topic>Догляд за собаками</topic>
                            <keywords>
                                <keyword>купання</keyword> 
                                <keyword>страх</keyword> 
                                <keyword>собака</keyword> 
                            </keywords>
                            <comments>
                                <comment id="comment2-1-1">
                                    <author userId="user4">Користувач4</author>
                                    <content>Якщо боїться собака, то варто поступово її обливати та зволожувати водою.</content>
                                    <timestamp>2023-03-15T14:00:00</timestamp>
